# This is a basic workflow that is manually triggered

name: Build and push edxapp image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_vault_pass:
    runs-on: ubuntu-latest
    env:
      VAULT_PASS: ${{ secrets.VAULT_PASS }}
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$VAULT_PASS" > .vault_pass.txt'
      - run: ls
