# This is a basic workflow that is manually triggered

name: Build and push edxapp image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  create_vault_pass:
    runs-on: ubuntu-latest
    steps:
      - name: Create .vault_pass.txt
        run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass.txt
      - name: Print contents of .vault_pass.txt
        run: cat .vault_pass.txt
